language: ruby
rvm:
- 2.6.0

cache: bundler

branches:
  only:
  - master
  - release

before_install:
- sudo apt-get install -y xfonts-75dpi xfonts-base
- wget https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.trusty_amd64.deb
- sudo dpkg -i wkhtmltox_0.12.5-1.trusty_amd64.deb

install:
- gem uninstall bundler
- gem install bundler --version '2.0.1'
- bundle install --path vendor/bundle

script: "bundle exec rake"

deploy:
  provider: pages
  local-dir: ./_site
  target-branch: gh-pages
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: release


env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
